### ISSUE TITLE
Create a Token

### ISSUE THREAD

**Issue by Slals** [From-Far-Away/ItSays#1]
The API has to know if the user who request the server is authenticated.

The idea is to create a token when a user is authenticated; the token is then storaged in the server side and is check every time a request is sent to the server.

**Comment by Slaals** [comment]
#4d8a5f487fbc6d77a637a83e32a843c6ce1f140d

**Comment by Slals** [comment]
Done 4d8a5f487fbc6d77a637a83e32a843c6ce1f140d
